# Generated by Django 6.0.1 on 2026-01-31 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentee',
            name='country',
            field=models.CharField(default='unknown', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mentee',
            name='name',
            field=models.CharField(default='Unknown', max_length=120),
            preserve_default=False,
        ),
    ]
