# Generated by Django 6.0.1 on 2026-01-31 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_mentee_country_mentee_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='interested_field',
            field=models.CharField(default='UnKnown', max_length=120),
            preserve_default=False,
        ),
    ]
