# Generated by Django 6.0.1 on 2026-01-30 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_mentor_cv_mentor_github_mentor_linkedin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='name',
            field=models.CharField(default='Unknown', max_length=120),
            preserve_default=False,
        ),
    ]
