# Generated by Django 6.0.1 on 2026-01-31 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userprofile_interested_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='interested_field',
            field=models.CharField(default='UnKnown', max_length=120),
            preserve_default=False,
        ),
    ]
