# Generated by Django 6.0.1 on 2026-02-01 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_mentor_interested_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='interested_field',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='interested_field',
            field=models.CharField(choices=[('Psychology', 'Psychology'), ('Medical', 'Medical'), ('Technology', 'Technology')], max_length=50),
        ),
    ]
