# Generated by Django 6.0.1 on 2026-01-30 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_mentee_user_alter_mentor_user'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='mentorrequest',
            index=models.Index(fields=['mentor', 'status'], name='core_mentor_mentor__a6dbd0_idx'),
        ),
        migrations.AddIndex(
            model_name='mentorrequest',
            index=models.Index(fields=['mentee', 'status'], name='core_mentor_mentee__12cded_idx'),
        ),
    ]
