# Generated by Django 6.0.1 on 2026-02-08 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_emailotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='eucation_field',
            field=models.CharField(choices=[('Diploma', 'Diploma'), ('Degree', 'Degree'), ('Masters', 'Masters'), ('PHD', 'PHD')], default='UnKnown', max_length=50),
            preserve_default=False,
        ),
    ]
