# Generated by Django 6.0.1 on 2026-02-08 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_userprofile_eucation_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='eucation_field',
            new_name='education',
        ),
    ]
